
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: quarkus-frontend-pipeline-
spec:
  pipelineRef:
    name: quarkus-frontend-pipeline
  params:
    - name: "git-url"
      value: "https://github.com/pittar-sandbox/serverless-frontend.git"
    - name: "git-revision"
      value: "main"
    - name: "app-name"
      value: "quarkus-frontend-app"
    - name: "namespace"
      value: "eventing-demo"
  workspaces:
    - name: build-workspace
      persistentVolumeClaim:
        claimName: build-workspace
    - name: maven-settings
      emptyDir: {}
      
