apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: math-channel-multiply 
spec:
  channel: 
    apiVersion: messaging.knative.dev/v1beta1
    kind: Channel
    name: math-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: serverless-multiply