apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: add-ping-source
spec:
  schedule: "*/1 * * * *" 
  jsonData: '{"x": 20.0, "y": 5.0}' 
  sink: 
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: serverless-add