apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless-add 
spec:
  template:
    spec:
      containers:
        - image: quay.io/pittar/serverless-quarkus:latest 
          env:
            - name: MATH_OPERATION 
              value: "+"